package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAGdan<M extends BaseAGdan<M>> extends Model<M> implements IBean {

	public void setGdanId(java.lang.Integer gdanId) {
		set("gdanId", gdanId);
	}

	public java.lang.Integer getGdanId() {
		return get("gdanId");
	}

	public void setGdanNum(java.lang.String gdanNum) {
		set("gdanNum", gdanNum);
	}

	public java.lang.String getGdanNum() {
		return get("gdanNum");
	}

	public void setMacNum(java.lang.String macNum) {
		set("macNum", macNum);
	}

	public java.lang.String getMacNum() {
		return get("macNum");
	}

	public void setMuJuNum(java.lang.String muJuNum) {
		set("muJuNum", muJuNum);
	}

	public java.lang.String getMuJuNum() {
		return get("muJuNum");
	}

	public void setCustNum(java.lang.String custNum) {
		set("custNum", custNum);
	}

	public java.lang.String getCustNum() {
		return get("custNum");
	}

	public void setMatNum(java.lang.String matNum) {
		set("matNum", matNum);
	}

	public java.lang.String getMatNum() {
		return get("matNum");
	}

	public void setGdanColor(java.lang.String gdanColor) {
		set("gdanColor", gdanColor);
	}

	public java.lang.String getGdanColor() {
		return get("gdanColor");
	}

	public void setBiaoZhunChanNeng(java.lang.Integer biaoZhunChanNeng) {
		set("biaoZhunChanNeng", biaoZhunChanNeng);
	}

	public java.lang.Integer getBiaoZhunChanNeng() {
		return get("biaoZhunChanNeng");
	}

	public void setLiLunZhouQi(java.lang.Integer liLunZhouQi) {
		set("liLunZhouQi", liLunZhouQi);
	}

	public java.lang.Integer getLiLunZhouQi() {
		return get("liLunZhouQi");
	}

	public void setMuXue(java.lang.Integer muXue) {
		set("muXue", muXue);
	}

	public java.lang.Integer getMuXue() {
		return get("muXue");
	}

	public void setDingDanQty(java.lang.Integer dingDanQty) {
		set("dingDanQty", dingDanQty);
	}

	public java.lang.Integer getDingDanQty() {
		return get("dingDanQty");
	}

	public void setShengChanQianShu(java.lang.Integer shengChanQianShu) {
		set("shengChanQianShu", shengChanQianShu);
	}

	public java.lang.Integer getShengChanQianShu() {
		return get("shengChanQianShu");
	}

	public void setPaiDanRiQi(java.util.Date paiDanRiQi) {
		set("paiDanRiQi", paiDanRiQi);
	}

	public java.util.Date getPaiDanRiQi() {
		return get("paiDanRiQi");
	}

	public void setJieShuRiQi(java.util.Date jieShuRiQi) {
		set("jieShuRiQi", jieShuRiQi);
	}

	public java.util.Date getJieShuRiQi() {
		return get("jieShuRiQi");
	}

	public void setIsUse(java.lang.String isUse) {
		set("isUse", isUse);
	}

	public java.lang.String getIsUse() {
		return get("isUse");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAddDate(java.util.Date addDate) {
		set("addDate", addDate);
	}

	public java.util.Date getAddDate() {
		return get("addDate");
	}

	public void setAddUser(java.lang.String addUser) {
		set("addUser", addUser);
	}

	public java.lang.String getAddUser() {
		return get("addUser");
	}

	public void setAltDate(java.util.Date altDate) {
		set("altDate", altDate);
	}

	public java.util.Date getAltDate() {
		return get("altDate");
	}

	public void setAltUser(java.lang.String altUser) {
		set("altUser", altUser);
	}

	public java.lang.String getAltUser() {
		return get("altUser");
	}

}
