package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebSysParm<M extends BaseWebSysParm<M>> extends Model<M> implements IBean {

	public void setParmId(java.lang.Long parmId) {
		set("parmId", parmId);
	}

	public java.lang.Long getParmId() {
		return get("parmId");
	}

	public void setParmKey(java.lang.String parmKey) {
		set("parmKey", parmKey);
	}

	public java.lang.String getParmKey() {
		return get("parmKey");
	}

	public void setParmValue(java.lang.String parmValue) {
		set("parmValue", parmValue);
	}

	public java.lang.String getParmValue() {
		return get("parmValue");
	}

	public void setParmGroup(java.lang.String parmGroup) {
		set("parmGroup", parmGroup);
	}

	public java.lang.String getParmGroup() {
		return get("parmGroup");
	}

	public void setParmRemark(java.lang.String parmRemark) {
		set("parmRemark", parmRemark);
	}

	public java.lang.String getParmRemark() {
		return get("parmRemark");
	}

}
