package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIoSignRec<M extends BaseIoSignRec<M>> extends Model<M> implements IBean {

	public void setSignRecId(java.lang.String signRecId) {
		set("signRecId", signRecId);
	}

	public java.lang.String getSignRecId() {
		return get("signRecId");
	}

	public void setCompId(java.lang.String compId) {
		set("compId", compId);
	}

	public java.lang.String getCompId() {
		return get("compId");
	}

	public void setCardNumber(java.lang.String cardNumber) {
		set("cardNumber", cardNumber);
	}

	public java.lang.String getCardNumber() {
		return get("cardNumber");
	}

	public void setSignN(java.lang.Integer signN) {
		set("signN", signN);
	}

	public java.lang.Integer getSignN() {
		return get("signN");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
