package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebRole<M extends BaseWebRole<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}

	public java.lang.String getRoleName() {
		return get("roleName");
	}

	public void setRoleFid(java.lang.Integer roleFid) {
		set("roleFid", roleFid);
	}

	public java.lang.Integer getRoleFid() {
		return get("roleFid");
	}

	public void setRoleRemark(java.lang.String roleRemark) {
		set("roleRemark", roleRemark);
	}

	public java.lang.String getRoleRemark() {
		return get("roleRemark");
	}

	public void setRoleCode(java.lang.String roleCode) {
		set("roleCode", roleCode);
	}

	public java.lang.String getRoleCode() {
		return get("roleCode");
	}

}
