package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebAccessLog<M extends BaseWebAccessLog<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Long logId) {
		set("logId", logId);
	}

	public java.lang.Long getLogId() {
		return get("logId");
	}

	public void setLogIP(java.lang.String logIP) {
		set("logIP", logIP);
	}

	public java.lang.String getLogIP() {
		return get("logIP");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setLogHandle(java.lang.String logHandle) {
		set("logHandle", logHandle);
	}

	public java.lang.String getLogHandle() {
		return get("logHandle");
	}

	public void setLogTime(java.util.Date logTime) {
		set("logTime", logTime);
	}

	public java.util.Date getLogTime() {
		return get("logTime");
	}

}
