package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKbDianshi01Rec<M extends BaseKbDianshi01Rec<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setMacNo(java.lang.String macNo) {
		set("macNo", macNo);
	}

	public java.lang.String getMacNo() {
		return get("macNo");
	}

	public void setZhuangTai(java.lang.String zhuangTai) {
		set("zhuangTai", zhuangTai);
	}

	public java.lang.String getZhuangTai() {
		return get("zhuangTai");
	}

	public void setMatName(java.lang.String matName) {
		set("matName", matName);
	}

	public java.lang.String getMatName() {
		return get("matName");
	}

	public void setBiaoZhunChanNeng(java.lang.Integer biaoZhunChanNeng) {
		set("biaoZhunChanNeng", biaoZhunChanNeng);
	}

	public java.lang.Integer getBiaoZhunChanNeng() {
		return get("biaoZhunChanNeng");
	}

	public void setZhuSuQty(java.lang.Integer zhuSuQty) {
		set("zhuSuQty", zhuSuQty);
	}

	public java.lang.Integer getZhuSuQty() {
		return get("zhuSuQty");
	}

	public void setYaJianQty(java.lang.Integer yaJianQty) {
		set("yaJianQty", yaJianQty);
	}

	public java.lang.Integer getYaJianQty() {
		return get("yaJianQty");
	}

	public void setZhuangXiangQty(java.lang.Integer zhuangXiangQty) {
		set("zhuangXiangQty", zhuangXiangQty);
	}

	public java.lang.Integer getZhuangXiangQty() {
		return get("zhuangXiangQty");
	}

	public void setBuLiangQty(java.lang.Integer buLiangQty) {
		set("buLiangQty", buLiangQty);
	}

	public java.lang.Integer getBuLiangQty() {
		return get("buLiangQty");
	}

	public void setBanCiDate(java.lang.String banCiDate) {
		set("banCiDate", banCiDate);
	}

	public java.lang.String getBanCiDate() {
		return get("banCiDate");
	}

	public void setBanBie(java.lang.String banBie) {
		set("banBie", banBie);
	}

	public java.lang.String getBanBie() {
		return get("banBie");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("createUser");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
