package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebUser<M extends BaseWebUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserNum(java.lang.String userNum) {
		set("userNum", userNum);
	}

	public java.lang.String getUserNum() {
		return get("userNum");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setUserPsw(java.lang.String userPsw) {
		set("userPsw", userPsw);
	}

	public java.lang.String getUserPsw() {
		return get("userPsw");
	}

	public void setUserCom(java.lang.String userCom) {
		set("userCom", userCom);
	}

	public java.lang.String getUserCom() {
		return get("userCom");
	}

	public void setUserMobile(java.lang.String userMobile) {
		set("userMobile", userMobile);
	}

	public java.lang.String getUserMobile() {
		return get("userMobile");
	}

	public void setUserEmail(java.lang.String userEmail) {
		set("userEmail", userEmail);
	}

	public java.lang.String getUserEmail() {
		return get("userEmail");
	}

	public void setUserRemark(java.lang.String userRemark) {
		set("userRemark", userRemark);
	}

	public java.lang.String getUserRemark() {
		return get("userRemark");
	}

}
