package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeType<M extends BaseNoticeType<M>> extends Model<M> implements IBean {

	public void setNoticeTypeId(java.lang.Integer noticeTypeId) {
		set("noticeTypeId", noticeTypeId);
	}

	public java.lang.Integer getNoticeTypeId() {
		return get("noticeTypeId");
	}

	public void setNoticeTypeName(java.lang.String noticeTypeName) {
		set("noticeTypeName", noticeTypeName);
	}

	public java.lang.String getNoticeTypeName() {
		return get("noticeTypeName");
	}

	public void setNoticeTypeOrd(java.lang.Integer noticeTypeOrd) {
		set("noticeTypeOrd", noticeTypeOrd);
	}

	public java.lang.Integer getNoticeTypeOrd() {
		return get("noticeTypeOrd");
	}

}
