package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAMatKucun<M extends BaseAMatKucun<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMatNo(java.lang.String matNo) {
		set("matNo", matNo);
	}

	public java.lang.String getMatNo() {
		return get("matNo");
	}

	public void setMatName(java.lang.String matName) {
		set("matName", matName);
	}

	public java.lang.String getMatName() {
		return get("matName");
	}

	public void setKucun(java.lang.Double kucun) {
		set("kucun", kucun);
	}

	public java.lang.Double getKucun() {
		return get("kucun");
	}

}
