package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebUserPsw<M extends BaseWebUserPsw<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserPsw(java.lang.String userPsw) {
		set("userPsw", userPsw);
	}

	public java.lang.String getUserPsw() {
		return get("userPsw");
	}

}
