package com.xp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setNoticeId(java.lang.Integer noticeId) {
		set("noticeId", noticeId);
	}

	public java.lang.Integer getNoticeId() {
		return get("noticeId");
	}

	public void setNoticeTypeId(java.lang.Integer noticeTypeId) {
		set("noticeTypeId", noticeTypeId);
	}

	public java.lang.Integer getNoticeTypeId() {
		return get("noticeTypeId");
	}

	public void setNoticeTitle(java.lang.String noticeTitle) {
		set("noticeTitle", noticeTitle);
	}

	public java.lang.String getNoticeTitle() {
		return get("noticeTitle");
	}

	public void setNoticeContent(java.lang.String noticeContent) {
		set("noticeContent", noticeContent);
	}

	public java.lang.String getNoticeContent() {
		return get("noticeContent");
	}

	public void setLastUpdate(java.util.Date lastUpdate) {
		set("lastUpdate", lastUpdate);
	}

	public java.util.Date getLastUpdate() {
		return get("lastUpdate");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

}
