package com.xp.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("a_gdan", "gdanId", AGdan.class);
		arp.addMapping("a_mac", "macNum", AMac.class);
		arp.addMapping("a_mac_fault", "macFaultNum", AMacFault.class);
		arp.addMapping("a_mac_fault_rec", "macFaultRecId", AMacFaultRec.class);
		arp.addMapping("a_mac_ton", "macTonId", AMacTon.class);
		arp.addMapping("a_mac_type", "macTypeId", AMacType.class);
		arp.addMapping("a_mat_kucun", "id", AMatKucun.class);
		arp.addMapping("io_origin_rec", "recId", IoOriginRec.class);
		arp.addMapping("io_sign_rec", "signRecId", IoSignRec.class);
		arp.addMapping("kb_dianshi_01", "id", KbDianshi01.class);
		arp.addMapping("kb_dianshi_01_rec", "id", KbDianshi01Rec.class);
		arp.addMapping("notice", "noticeId", Notice.class);
		arp.addMapping("notice_type", "noticeTypeId", NoticeType.class);
		arp.addMapping("web_access_log", "logId", WebAccessLog.class);
		arp.addMapping("web_auth_obj", "authId", WebAuthObj.class);
		arp.addMapping("web_menu", "menuId", WebMenu.class);
		arp.addMapping("web_role", "roleId", WebRole.class);
		// Composite Primary Key order: menuId,roleId
		arp.addMapping("web_role_menu", "menuId,roleId", WebRoleMenu.class);
		arp.addMapping("web_sys_parm", "parmId", WebSysParm.class);
		arp.addMapping("web_user", "userId", WebUser.class);
		arp.addMapping("web_user_psw", "userId", WebUserPsw.class);
		// Composite Primary Key order: roleId,userId
		arp.addMapping("web_user_role", "roleId,userId", WebUserRole.class);
	}
}

