package com.xp.model;

import com.xp.model.base.BaseAGdan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AGdan extends BaseAGdan<AGdan> {
	public static final AGdan dao = new AGdan();
}
