package com.xp.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.xp.model.base.BaseAMac;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMac extends BaseAMac<AMac> {
	public static final AMac dao = new AMac();
	
	public List<Record> listOrderByMacNum(){
		String sql = "select *,case am.isUse when 'y' then '在用' else '停用' end isUse "
				+ "from a_mac am "
				+ "left join a_mac_ton amt on amt.macTonId=am.macTonId "
				+ "left join a_mac_type amy on amy.macTypeId=am.macTypeId "
				+ "order by macNum";
		List<Record> rows = Db.find(sql);
		return rows;
	}
	
}
