package com.xp.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.xp.model.base.BaseAMacTon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMacTon extends BaseAMacTon<AMacTon> {
	public static final AMacTon dao = new AMacTon();
	
	public List<Record> list(){
		String sql = "select * from a_mac_ton";
		List<Record> rows = Db.find(sql);
		return rows;
	}
}
