package com.xp.model;

import com.xp.model.base.BaseAMacFault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMacFault extends BaseAMacFault<AMacFault> {
	public static final AMacFault dao = new AMacFault();
}
