package com.xp.model;

import com.xp.model.base.BaseAMacType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMacType extends BaseAMacType<AMacType> {
	public static final AMacType dao = new AMacType();
}
