package com.xp.model;

import com.xp.model.base.BaseAMacFaultRec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMacFaultRec extends BaseAMacFaultRec<AMacFaultRec> {
	public static final AMacFaultRec dao = new AMacFaultRec();
}
