package com.xp.model;

import com.xp.model.base.BaseAMatKucun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AMatKucun extends BaseAMatKucun<AMatKucun> {
	public static final AMatKucun dao = new AMatKucun();
}
