package com.xp.model;

import com.xp.model.base.BaseIoOriginRec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IoOriginRec extends BaseIoOriginRec<IoOriginRec> {
	public static final IoOriginRec dao = new IoOriginRec();
}
