package com.xp.model;

import com.xp.model.base.BaseIoSignRec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IoSignRec extends BaseIoSignRec<IoSignRec> {
	public static final IoSignRec dao = new IoSignRec();
}
