package com.xp.model;

import com.xp.model.base.BaseKbDianshi01Rec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KbDianshi01Rec extends BaseKbDianshi01Rec<KbDianshi01Rec> {
	public static final KbDianshi01Rec dao = new KbDianshi01Rec();
}
