package com.xp.model;

import com.xp.model.base.BaseKbDianshi01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KbDianshi01 extends BaseKbDianshi01<KbDianshi01> {
	public static final KbDianshi01 dao = new KbDianshi01();
}
