package com.xp.model;

import java.util.List;

import com.xp.model.base.BaseNoticeType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeType extends BaseNoticeType<NoticeType> {
	public static final NoticeType dao = new NoticeType();
	
	public List<NoticeType> listNoticeType(){
		String sql = "select * from notice_type order by noticeTypeOrd";
		List<NoticeType> rows = find(sql);
		return rows;
	}
}
