package com.xp.model;

import java.util.List;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.xp.model.base.BaseNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	public static final Notice dao = new Notice();
	

	public Page<Notice> listNotice(
			int page,
			int pageSize,
			String where,
			String whereMap,
			String order
			){
		order = StrKit.notBlank(order)?order:"a.noticeId desc";
		Object[] whereArr = {};
		if(!where.equals("")){
			where = " where " + where;
			whereArr = whereMap.split("~@~");
		}
		Page<Notice> rows = paginate(
				page, 
				pageSize, 
				"select a.*,b.noticeTypeName", 
				"from notice a "
				+ "left join notice_type b on b.noticeTypeId=a.noticeTypeId"
				+ where
				+ " order by " + order,
				whereArr
				);
		return rows;
	}
	
	public List<Notice> listNoticeByTypeId(int typeId){
		String sql = "select * from notice "
				+ "where noticeTypeId=? "
				+ "order by lastUpdate desc "
				+ "limit 5";
		List<Notice> rows = find(sql,typeId);
		return rows;
	}
}
