package com.xp.model;

import java.util.List;
import java.util.TreeMap;

import com.xp.model.base.BaseViewListUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewListUserMenu extends BaseViewListUserMenu<ViewListUserMenu> {
	public static final ViewListUserMenu dao = new ViewListUserMenu();
	

	public List<ViewListUserMenu> listUserMenu(int userId){
		String sql = "select * from view_list_user_menu "
				+ "where userId=? and isShow=? group by menuId order by menuOrd";
		return find(sql,userId,"y");
	}
	
	public TreeMap<String, String> mapUserCanAccess(int userId){
		String sql = "select menuUrl from view_list_user_menu "
				+ "where userId=?";
		List<ViewListUserMenu> rows = find(sql,userId);
		TreeMap<String, String> userCanAccess = new TreeMap<>();
		for(ViewListUserMenu row : rows){
			userCanAccess.put("/"+row.getStr("menuUrl"), "Y");
		}
		return userCanAccess;
	}
}
