package com.xp.model;

import com.xp.model.base.BaseViewListUserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewListUserAuth extends BaseViewListUserAuth<ViewListUserAuth> {
	public static final ViewListUserAuth dao = new ViewListUserAuth();
}
