package com.xp.model;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

import com.jfinal.kit.StrKit;
import com.xp.constant.Info;
import com.xp.model.base.BaseViewListUserRole;
import com.xp.util.XPFunctions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewListUserRole extends BaseViewListUserRole<ViewListUserRole> {
	public static final ViewListUserRole dao = new ViewListUserRole();
	
	//分页查询用户
	public List<ViewListUserRole> listUserRole(
			int userId
			){
		String sql = "select * from "
				+ "view_list_user_role "
				+ "where userId=?";
		List<ViewListUserRole> rows = find(sql,userId);
		return rows;
	}

	public TreeMap<String, String> mapUserRole(int userId){
		String sql = "select roleCode "
				+ "from view_list_user_role "
				+ "where userId=?";
		List<ViewListUserRole> rows = find(sql,userId);
		TreeMap<String, String> mapUserRole = new TreeMap<>();
		List<String> roleCodeList = new ArrayList<>();
		for(ViewListUserRole row : rows){
			String roleCode = row.getRoleCode();
			if(StrKit.notBlank(roleCode)){
				mapUserRole.put(roleCode, "Y");
				roleCodeList.add(roleCode);
			}
		}
		mapUserRole.put(Info.ALL_ROLE_CODE, XPFunctions.join(",", roleCodeList));
		return mapUserRole;
	}
}
