package com.xp.model;

import java.util.List;

import com.xp.model.base.BaseViewListRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewListRoleMenu extends BaseViewListRoleMenu<ViewListRoleMenu> {
	public static final ViewListRoleMenu dao = new ViewListRoleMenu();
	
	//分页查询用户
	public List<ViewListRoleMenu> listRoleMenu(
			int roleId
			){
		List<ViewListRoleMenu> rows = find("select * from view_list_role_menu where roleId=?", roleId);
		return rows;
	}
}
