package com.xp.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.xp.model.base.BaseWebAccessLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebAccessLog extends BaseWebAccessLog<WebAccessLog> {
	public static final WebAccessLog dao = new WebAccessLog();
	
	public void addLog(String ip,Integer userId){
		addLog(ip,userId,"login");
	}
	
	public void addLog(String logIP,Integer userId,String handle){
		WebAccessLog row = new WebAccessLog();
		row.set("logIP", logIP);
		row.set("userId", userId);
		row.set("logHandle", handle);
		row.save();
	}
	
	public List<WebAccessLog> logRecently(Integer userId,Integer days){
		String sql = "select * "
				+ "from web_access_log "
				+ "where userId=? "
				+ "and TO_DAYS(NOW()) - TO_DAYS(logTime) <= ? "
				+ "order by logId desc";
		return find(sql,userId,days);
	}
	
	public Page<WebAccessLog> logRecently(int page,int rows,String where,String whereMap){
		Object[] whereArr = {};
		if(!where.equals("")){
			where = " where " + where;
			whereArr = whereMap.split("~@~");
		}else{
			where = " where TO_DAYS(NOW()) - TO_DAYS(logTime) <= 30 ";
		}
		Page<WebAccessLog> logs = paginate(
				page, 
				rows, 
				"select *", 
				"from web_access_log a "
				+ "left join web_user b on b.userId=a.userId "
				+ where
				+ " order by a.logId desc ",
				whereArr
				);
		return logs;
		
	}
}
