package com.xp.model;

import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.xp.model.base.BaseWebAuthObj;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebAuthObj extends BaseWebAuthObj<WebAuthObj> {
	public static final WebAuthObj dao = new WebAuthObj();
	
	public List<WebAuthObj> listAuthObj(int roleId){
		String sql = "select * from web_auth_obj "
				+ "where roleId = ? order by authName,authValue";
		List<WebAuthObj> rows = find(sql,roleId);
		return rows;
	}
	
	@Before(Tx.class)
	public boolean saveAuthObj(int roleId,List<WebAuthObj> rows){
		Db.update("delete from web_auth_obj where roleId = ?", roleId);
		for(WebAuthObj row : rows){
			row.save();
		}
		
		return true;
	}
	
	public List<WebAuthObj> listUserAuth(int userId){
		String sql = "select c.userId,a.authName,a.authValue "
				+ "from web_auth_obj a "
				+ "left join web_role b on b.roleId=a.roleId "
				+ "left join web_user_role c on c.roleId=b.roleId "
				+ "where c.userId=?";
		List<WebAuthObj> rows = find(sql,userId);
		return rows;
	}
	
	public String getTargetAuth(int userId,String targetAuth){
		String sql = "select c.userId,a.authName,a.authValue "
				+ "from web_auth_obj a "
				+ "left join web_role b on b.roleId=a.roleId "
				+ "left join web_user_role c on c.roleId=b.roleId "
				+ "where c.userId=? "
				+ "and a.authName=? ";
		WebAuthObj row = findFirst(sql,userId,targetAuth);
		if(row == null)
			return "";
		return row.getStr("authValue");
	}
}
