package com.xp.model;

import java.util.List;

import com.xp.model.base.BaseWebMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebMenu extends BaseWebMenu<WebMenu> {
	public static final WebMenu dao = new WebMenu();
	
	public List<WebMenu> listMenu(){
		List<WebMenu> rows = find("select * from web_menu order by menuOrd");
		return rows;
	}
}
