package com.xp.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.xp.model.base.BaseWebRoleMenu;
import com.xp.util.XPFunctions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebRoleMenu extends BaseWebRoleMenu<WebRoleMenu> {
	public static final WebRoleMenu dao = new WebRoleMenu();
	
	@Before(Tx.class)
	public boolean saveRoleMenu(int roleId,List<WebRoleMenu> rows){
		Db.update("delete from web_role_menu where roleId = ?", roleId);
		if(rows.isEmpty()){
			return true;
		}
		String sql = "insert into web_role_menu (menuId,roleId) values ";
		List<String> valList = new ArrayList<>();
		for(WebRoleMenu row : rows){
			valList.add("('"+row.getMenuId()+"','"+roleId+"')");
		}
		sql = sql + XPFunctions.join(",", valList);
		Db.update(sql);
		return true;
	}
}
