package com.xp.model;

import java.util.List;

import com.xp.model.base.BaseWebRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebRole extends BaseWebRole<WebRole> {
	public static final WebRole dao = new WebRole();
	
	public List<WebRole> listRole(){
		List<WebRole> roles = find("select * from web_role");
		return roles;
	}
}
