package com.xp.model;

import java.util.List;

import com.xp.model.base.BaseWebSysParm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebSysParm extends BaseWebSysParm<WebSysParm> {
	public static final WebSysParm dao = new WebSysParm();

	public String getValueOfKey(String key,String group){
		WebSysParm row = findFirst(
				"SELECT parmValue FROM web_sys_parm WHERE parmKey=? AND parmGroup=?", 
				key,
				group);
		if(row == null){
			return "";
		}
		return row.getStr("parmValue");
	}
	
	public List<WebSysParm> listSysParm(){
		String sql = "select * from web_sys_parm";
		List<WebSysParm> rows = find(sql);
		return rows;
	}
}
