package com.xp.model;

import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.xp.model.base.BaseWebUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebUserRole extends BaseWebUserRole<WebUserRole> {
	public static final WebUserRole dao = new WebUserRole();
	
	@Before(Tx.class)
	public boolean saveUserRole(int userId,List<WebUserRole> rows){
		Db.update("delete from web_user_role where userId = ?", userId);
		for(WebUserRole row : rows){
			row.save();
		}
		
		return true;
	}
}
