package com.xp.model;

import com.xp.model.base.BaseWebUserPsw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebUserPsw extends BaseWebUserPsw<WebUserPsw> {
	public static final WebUserPsw dao = new WebUserPsw();
}
