package com.xp.model;

import java.util.List;
import java.util.TreeMap;

import javax.servlet.http.HttpSession;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.xp.model.base.BaseWebUser;
import com.xp.util.XPFunctions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebUser extends BaseWebUser<WebUser> {
	public static final WebUser dao = new WebUser();

	public boolean saveUser(WebUser user) {
		String udp = WebSysParm.dao.getValueOfKey("user_default_passowrd", "baseweb");
		user.set("userPsw", XPFunctions.saltMD5(udp));
		return user.save();
	}

	public WebUser singleUserByUserNum(String userNum) {
		String sql = "select * from web_user where userNum = ?";
		return findFirst(sql, userNum);
	}

	public boolean resetPsw(int userId) {
		String udp = WebSysParm.dao.getValueOfKey("user_default_passowrd", "baseweb");
		if (StrKit.isBlank(udp)) {
			udp = "123456";
		}
		WebUser user = new WebUser();
		user.set("userPsw", XPFunctions.saltMD5(udp));
		user.setUserId(userId);
		return user.update();
	}

	public boolean delUser(int userId) {
		WebUser user = new WebUser();
		user.setUserId(userId);
		return user.delete();
	}
	
	public void delUser(String userNum) {
		String sql = "delete from web_user where userNum=?";
		Db.update(sql, userNum);
	}

	public boolean updateUserPsw(WebUser user) {
		if (StrKit.notBlank(user.getStr("userPsw"))) {
			user.set("userPsw", XPFunctions.saltMD5(user.getStr("userPsw")));
		}
		return user.update();
	}
	
	//将用户信息写入session
	public static void initUserInfoIntoSession(WebUser user,HttpSession session){
		List<ViewListUserMenu> listUserMenu = 
				ViewListUserMenu.dao.listUserMenu(user.getUserId());
		TreeMap<String, String> mapUserCanAccess = 
				ViewListUserMenu.dao.mapUserCanAccess(user.getUserId());
		TreeMap<String, String> mapUserRole = 
				ViewListUserRole.dao.mapUserRole(user.getUserId());
		session.setAttribute("User", user);
		session.setAttribute("userMenu", listUserMenu);
		session.setAttribute("userCanAccess", mapUserCanAccess);
		session.setAttribute("userRole", mapUserRole);
	}
}
